<?php
/**
 * Created by PhpStorm.
 * User: hanishkeloth
 * Date: 09/01/17
 * Time: 10:45 AM
 */

function call_order_menu() {
    $items = array();

    $items['admin/call-order/register'] = array( //this creates a URL that will call this form at "examples/form-example"
        'title' => 'User create', //page title
        'description' => 'A form to mess around with.',
        'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
        'page arguments' => array('call_order_form'), //put the name of the form here
        'access callback' => 'call_order_user_has_role',   
        'access arguments' => array('Call Center', 'administrator'),
    );

    return $items;
}

function call_order_user_has_role() {  
  global $user;
  $roles = func_get_args();
  foreach ($roles as $role) {
    if (in_array($role, $user->roles)) {
      return TRUE;
    }
  }
  return FALSE; 
}

function call_order_form($form, &$form_state) {

    $form['name'] = array(
        '#type' => 'textfield', //you can find a list of available types in the form api
        '#title' => 'Mobile Number',
        //'#size' => 10,
        //'#maxlength' => 10,
        '#required' => TRUE, //make this field required
    );

    $form['submit_button'] = array(
        '#type' => 'submit',
        '#value' => t('Register User!'),
    );

    return $form;
}

function call_order_form_validate($form, &$form_state) {
    $user = user_load_by_name($form_state['values']['name']);
    if($user) {
        //form_set_error(t('Price must be a positive number.'));
        form_set_error('name', t('User Already Exist.'));
    }
}

function call_order_form_submit($form, &$form_state) {
       $mobile_number = $form_state['values']['name'];
    $new_user = array(
        'name' => $mobile_number,
        'pass' => $mobile_number, // note: do not md5 the password
        'mail' => $mobile_number.'@kirana11.com',
        'status' => 1,
        'init' =>  $mobile_number.'@kirana11.com',
        'roles' => array(
            DRUPAL_AUTHENTICATED_RID => 'authenticated user',
            5 => 'customer',
        ),
    );

// The first parameter is sent blank so a new user is created.
    user_save('', $new_user);
    $form_state['redirect'] = 'admin/Store-select';

}


