<?php
/**
 * Implements hook_init().
 */
function commerce_marketplace_kirana11_cart_init() {
  drupal_add_js(drupal_get_path('module', 'commerce_marketplace_kirana11_cart') . '/js/script.js');
}

/**
 * Implements hook_block_info().
 */
function commerce_marketplace_kirana11_cart_block_info() {
  $blocks = [];

  $blocks['check_location_change'] = array(
    'info' => t('Check location change with non-empty cart'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function commerce_marketplace_kirana11_cart_block_view($delta = '') {
  $block = [];

  switch ($delta) {
    case 'check_location_change':
      $block['content'] = commerce_marketplace_kirana11_cart_block_content();
      break;
  }

  return $block;
}

function commerce_marketplace_kirana11_cart_block_content() {
  global $user;
  $html_location_change = 'EMPTY_CART';

  $user_order_in_cart = commerce_cart_order_load($user->uid);

  if ($user_order_in_cart) {
    $html_location_change = '<div class="not-empty-location">';
    $html_location_change .= 'You have cart item(s). Change location will empty the current cart. Do you want to continue?';
    $html_location_change .= '<br/><input type="button" id="click-no" class="click-no" value="No" /> <input type="button" id="click-yes" class="click-yes" value="Yes" />';
    $html_location_change .= '</div>';
  }

  return $html_location_change;
}

/**
 * Implements hook_menu().
 */
function commerce_marketplace_kirana11_cart_menu() {
  $items = array();

  $items['empty_cart_orders'] = array(
    'title' => t('Empty the cart orders'),
    'page callback' => 'commerce_marketplace_kirana11_cart_empty_cart_order',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Remove all the orders (from each store) in the cart for the current logged in user.
 */
function commerce_marketplace_kirana11_cart_empty_cart_order() {
  global $user;

  if ($orders = commerce_marketplace_cart_order_load_multiple($user->uid)) {
    foreach ($orders as $order) {
      commerce_cart_order_empty($order);
    }
  }

  return drupal_json_output('CART_EMPTY');
}

function commerce_marketplace_kirana11_cart_form_commerce_cart_add_to_cart_form_alter(&$form, &$form_state) {
  $form['submit']['#ajax'] = array(
    'callback' => 'commerce_ajax_cart_callback',
  );

  global $user;

  $form['submit']['#attributes']['value'] = t('Add to');
  $form['submit']['#prefix'] = '<div class="add-to-cart-div">';
  $form['submit']['#suffix'] = '</div>';

  // Only valid for logged in users, because of Varnish and other caches.
  if (!empty($user->uid)) {
    $line_item = $form_state['line_item'];

    // Check if it's in their cart.
    $cart_order_product_ids = commerce_marketplace_kirana11_cart_get_items_in_cart();

    if (!empty($cart_order_product_ids) && !empty($line_item->commerce_product)) {
      foreach ($cart_order_product_ids as $order_number =>  $cart_product_ids) {
        $cart_product_id_list = array_keys($cart_product_ids);

        $line_item_wrapper = entity_metadata_wrapper('commerce_line_item', $line_item);

        if (in_array($line_item_wrapper->commerce_product->product_id->value(), $cart_product_id_list)) {

          $quantity = 1;
          $order = commerce_order_load($order_number);

          if (!empty($order)) {
            if (count($order->commerce_line_items) > 0) {
              $line_items = $order->commerce_line_items;

              foreach ($line_items['und'] as $key => $value) {
                $line_item = commerce_line_item_load($value['line_item_id']);
                $products = $line_item->commerce_product['und'];

                foreach ($products as $product_key => $product_value) {
                  if ($line_item_wrapper->commerce_product->product_id->value() == $product_value['product_id']) {
                    $line_item = commerce_line_item_load($value['line_item_id']);
                    $quantity = floor($line_item->quantity);
                  }
                }
              }
            }
          }


          $form['submit']['#disabled'] = TRUE;
          $form['submit']['#value'] = t('In your cart!');
          $form['submit']['#type'] = 'hidden';

          $form['minus'] = array(
            '#type' => 'button',
            '#value' => t('-')
          );

          $form['cart_count'] = array(
            '#type' => 'textfield',
            '#title' => t('Cart count'),
            '#default_value' => 1,
            '#value' => $quantity,
            '#prefix' => '<div id="my_unique_id_' . $form['#form_id'] . '" class="add-to-cart-button">',
            '#suffix' => '</div>'
          );

          $form['plus'] = array(
            '#type' => 'button',
            '#value' => t('+'),
            '#ajax' => array(
              'callback' => 'click_on_plus',
              'wrapper' => 'my_unique_id_' . $form['#form_id'],
            ),
          );

          $form['product_id'] = array(
            '#type' => 'hidden',
            '#value' => $line_item_wrapper->commerce_product->product_id->value(),
          );
        }
      }
    }
  }

  return $form;
}

function commerce_ajax_cart_callback($form, &$form_state) {
  global $user;

  $form = drupal_rebuild_form($form['#form_id'], $form_state, $form);

  $commands[] = ajax_command_replace('.' . drupal_html_class($form['#form_id']), drupal_render($form));
  $commands[] = array(
    'command' => 'commerceAjaxCartFireTrigger',
    'data' => $form['#form_id'],
  );

  $form_state['rebuild'] = TRUE;

  return array(
    '#type' => 'ajax',
    '#commands' => $commands,
  );
}

function click_on_plus($form, $form_state) {
  global $user;

  $quantity = $form_state['values']['cart_count'];
  $product_id = $form_state['values']['product_id'];

  $cart_order_product_ids = commerce_marketplace_kirana11_cart_get_items_in_cart();

  if (!empty($cart_order_product_ids)) {
    foreach ($cart_order_product_ids as $order_number =>  $cart_product_ids) {
      $cart_product_id_list = array_keys($cart_product_ids);

      if (in_array($product_id, $cart_product_id_list)) {
        if ($user) {
          if ($orders = commerce_marketplace_cart_order_load_multiple($user->uid)) {
            foreach ($orders as $order) {
              if (!empty($order)) {
                if ($order->order_number == $order_number) {
                  if (count($order->commerce_line_items) > 0) {
                    $line_items = $order->commerce_line_items;

                    foreach ($line_items['und'] as $key => $value) {
                      $line_item = commerce_line_item_load($value['line_item_id']);
                      $products = $line_item->commerce_product['und'];

                      foreach ($products as $product_key => $product_value) {
                        if ($product_id == $product_value['product_id']) {
                          $line_item = commerce_line_item_load($value['line_item_id']);
                          $line_item->quantity = ++$quantity;

                          commerce_line_item_save($line_item);

                          $form['cart_count']['#value'] = $line_item->quantity;
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }

  return $form['cart_count'];
}

/**
 * Helper function to return an array of product_ids of the user's current cart.
 */
function commerce_marketplace_kirana11_cart_get_items_in_cart() {
  global $user;
  $cart_product_ids = &drupal_static(__FUNCTION__);

  if (!$cart_product_ids) {
    if ($orders = commerce_marketplace_cart_order_load_multiple($user->uid)) {
      foreach ($orders as $order) {
        if (!empty($order)) {
          $order_wrapper = entity_metadata_wrapper('commerce_order', $order);

          foreach ($order_wrapper->commerce_line_items as $delta => $line_item_wrapper) {
            if (!empty($line_item_wrapper->commerce_product)) {
              $product_wrapper = $line_item_wrapper->commerce_product;
              $type = $product_wrapper->type->value();
              $product_id = $product_wrapper->product_id->value();
              $cart_product_ids[$order->order_number][$product_id] = $type;
            }
          }
        }
      }
    }
  }

  return $cart_product_ids;
}

/**
 * Continue Shopping cart button added
 */
function commerce_marketplace_kirana11_cart_form_views_form_commerce_cart_form_default_alter(&$form, &$form_state, $form_id) {
  $form['actions']['continue_shopping'] = array(
    '#type' => 'button',
    '#value' => t('Continue Shopping'),
    '#weight' => -999,
  );
  /*if (isset($_SERVER['HTTP_REFERER']) && strlen($_SERVER['HTTP_REFERER'])) {
    // if user comes from product detail page, redirect user to previous page
    $form['actions']['continue_shopping']['#attributes'] = array('ONCLICK' => "history.go(-1); return false;");
  } else {
    // redirect user to product list page 'store' by default
    $form['actions']['continue_shopping']['#attributes'] = array('ONCLICK' => "window.location.href='" . url('store') . "'; return false;");
  }*/
  $form['actions']['continue_shopping']['#attributes'] = array('ONCLICK' => "history.go(-1); return false;");
}