<?php
/**
 * Created by PhpStorm.
 * User: hanishkeloth
 * Date: 07/01/17
 * Time: 10:45 AM
 */
require drupal_get_path('module', 'kirana11_otp') . '/class/textlocal.class.php';
/**
 * Implements hook_form_alter()
 */
function kirana11_otp_form_alter(&$form, &$form_state, $form_id) {

    if($form_id == 'user_register_form') {
      $form['account']['name']['#title'] = t('Mobile Number');
      $form['account']['name']['#weight'] = 200;

      $form['kirana11_otp_send_otp'] = array(
        '#type' => 'button',
        '#value' => t('Send OTP'),
        '#submit' => array('poll_more_choices_submit'), // If no javascript action.
        '#weight' => 3,
        '#ajax' => array(
          'callback' => 'kirana11_otp_send_otp_callback',
        ),
        '#attributes' => array('class' => array('otp-send-button')),
      );

      $form['kirana11_otp'] = array(
        '#type' => 'textfield',
        '#title' => t('OTP'),
        '#size' => 15,
        '#weight' => 3,
        '#maxlength' => 15,
        '#required' => TRUE,
        '#attributes' => array(
          'placeholder' => t('Enter OTP'),
        ),
      );

      $form['#validate'][] = 'kirana11_otp_form_validate';
    }
}

function kirana11_otp_send_otp_callback(&$form, &$form_state) {
    //form_set_error($form, t('Please enter a valid email address.'));
    $mobile_no = $form_state['complete form']['account']['name']['#value'];

    //drupal_set_message($mobile_no);
    $six_digit_random_number = mt_rand(100000, 999999);

    $_SESSION['kirana11_otp'] = $six_digit_random_number;
    $message = "Kirana11 OTP $six_digit_random_number";
    // Authorisation details.
    // Authorisation details.
    $username = "hanishkeloth@icloud.com";
    $hash = "4101975b3d1bb3d788e3c503734b75b4d765e509";

    // Config variables. Consult http://api.textlocal.in/docs for more info.
    $test = "0";

    // Data for text message. This is the text message data.
    $sender = "KIRANA"; // This is who the message appears to be from.
    $numbers = $mobile_no; // A single number or a comma-seperated list of numbers
    //$message = "Kirana11 OTP".$six_digit_random_number;
    // 612 chars or less
    // A single number or a comma-seperated list of numbers
    $message = urlencode($message);
    $data = "username=".$username."&hash=".$hash."&message=".$message."&sender=".$sender."&numbers=".$numbers."&test=".$test;
    $ch = curl_init('http://api.textlocal.in/send/?');
    curl_setopt($ch, CURLOPT_POST, true);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $result = curl_exec($ch); // This is the result from the API
    curl_close($ch);
    //$succ = $response;
    //twilio_send($mobile_no,$message,$country_codes);

    drupal_json_output($result);
    drupal_exit();

}

function kirana11_otp_form_validate($form, &$form_state) {

    $kirana11_otp =  $form_state['values']['kirana11_otp'];
    if(isset($_SESSION['kirana11_otp']) != isset($kirana11_otp)) {
        form_set_error('kirana11_otp', t('OTP doesn\'t match'));
    }
    //$_SESSION['twilio_otp_country_codes'] = $form_state['values']['twilio_otp_country_codes'];
    //$_SESSION['twilio_otp_mobile'] = $form_state['values']['twilio_otp_mobile'];
}