<?php
/**
 * Created by PhpStorm.
 * User: Vimala
 * Date: 1/11/2017
 * Time: 5:46 PM
 */

/**
 * Implements hook_init().
 */
function custom_address_book_init() {
    drupal_add_js(drupal_get_path('module', 'geocoder_location_handler') . '/js/detect_location.js',array('weight' => 1));
    drupal_add_js(drupal_get_path('module', 'custom_address_book') . '/js/address_book.js', array('weight' => 2));

}

/**
 * Implements hook_form_alter().
 */
function custom_address_book_form_alter(&$form, &$form_state, $form_id) {
    if($form_id == 'commerce_addressbook_customer_profile_form') {
        $form['commerce_customer_address'][LANGUAGE_NONE][0]['street_block']['premise']['#title'] = t('Area');
        $form['commerce_customer_address'][LANGUAGE_NONE][0]['street_block']['premise']['#disabled'] = TRUE;
        $form['commerce_customer_address'][LANGUAGE_NONE][0]['street_block']['premise']['#value'] = $_SESSION['k11_current_location'];
        $form['field_location_coordinates'][LANGUAGE_NONE][0]['value']['#default_value'] = $_SESSION['k11_user_coordinates'];
        $form['field_location_coordinates']['#access'] = FALSE;
    }
    if($form_id == 'user_addressbook_address_form') {
        $form['user_addressbook_address'][LANGUAGE_NONE][0]['street_block']['premise']['#title'] = t('Area');
        $form['user_addressbook_address'][LANGUAGE_NONE][0]['street_block']['premise']['#disabled'] = TRUE;
        $form['user_addressbook_address'][LANGUAGE_NONE][0]['street_block']['premise']['#value'] = $_SESSION['k11_current_location'];
        $form['field_location_coordinates'][LANGUAGE_NONE][0]['value']['#default_value'] = $_SESSION['k11_user_coordinates'];
        $form['user_addressbook_address'][LANGUAGE_NONE][0]['locality_block']['postal_code']['#required'] = FALSE;
        $form['field_location_coordinates']['#access'] = FALSE;
    }

    if($form_id == 'commerce_checkout_form_addresses'){
        $form['user_addressbook']['commerce_customer_address'][LANGUAGE_NONE][0]['locality_block']['postal_code']['#required'] = FALSE;
        $form['user_addressbook']['commerce_customer_address'][LANGUAGE_NONE][0]['street_block']['premise']['#title'] = t('Area');
        $form['user_addressbook']['commerce_customer_address'][LANGUAGE_NONE][0]['street_block']['premise']['#disabled'] = TRUE;
        $form['user_addressbook']['commerce_customer_address'][LANGUAGE_NONE][0]['street_block']['premise']['#value'] = $_SESSION['k11_current_location'];
        $form['user_addressbook']['field_location_coordinates'][LANGUAGE_NONE][0]['value']['#default_value'] = $_SESSION['k11_user_coordinates'];
        $form['user_addressbook']['commerce_customer_address'][0]['locality_block']['postal_code']['#required'] = FALSE;
        $form['user_addressbook']['field_location_coordinates']['#access'] = FALSE;

    }
}

/**
 * Disable Billing Information checkout page.
 */
/*function custom_address_book_commerce_checkout_pane_info_alter(&$checkout_pane) {
    global $user;

    foreach ($checkout_pane as $pane_name => & $pane_data) {
        if ($pane_name == 'customer_profile_shipping') {
            $order = commerce_cart_order_load($user->uid);
            if (!empty($order->data)){
                unset($checkout_pane['customer_profile_billing']);
            }
        }
    }
}*/

/**
 * Implements hook_commerce_checkout_pane_info_alter
 */
function custom_address_book_commerce_checkout_pane_info_alter(&$checkout_panes) {
    //echo "<pre>";print_r($checkout_panes);
  if(isset($checkout_panes['user_addressbook'])){
    $checkout_panes['user_addressbook']['callbacks']['checkout_form_validate'] = 'custom_address_book_commerce_shipping_pane_validate';
  }
}

/**
 * Checkout pane validation override to ensure valid shipping method for address
 */
function custom_address_book_commerce_shipping_pane_validate(&$form, &$form_state, $checkout_pane, $order) {
  $pane_id = reset($form_state['triggering_element']['#array_parents']);
  
  if (empty($form_state['order']->data['addresses'])) {
    drupal_set_message(t('Please select Address'), 'error');
    $form_state['pane_' . $pane_id]['mode'] = 'select_address';
    $form_state['pane_' . $pane_id]['action'] = 'select_address';
    $form_state['rebuild'] = TRUE;
  }
  else{
    return TRUE;
  }
}