<?php
/**
 * @file
 * Code for the Kirana11 Products feature.
 */

include_once 'kirana11_products.features.inc';

/**
 * Implements hook_form_alter().
 * @param $form
 * @param $form_state
 * @param $form_id
 */
function kirana11_products_form_alter(&$form, &$form_state, $form_id){
    if (isset($form_state['view']) && $form_state['view']->name == 'category_products' && $form_id == 'views_exposed_form') {
        global $base_url;
        $link = url(current_path());
        $form['#action'] = $base_url . '/'.$link;
    }
}

/**
 * Function to get all the Category terms.
 * @param $tid
 */
function _get_taxonomy_tree($tid){
    $term = taxonomy_term_load($tid);
    $terms = taxonomy_get_tree($term->vid);

    $main_term_list =   get_sibilings($terms, 0);

    foreach ($main_term_list as &$item) {
        $item['children'] = get_sibilings($terms, $item['tid']);
    }

    foreach ($main_term_list as &$first_level) {
        foreach ($first_level['children'] as &$second_level) {
            $second_level['children'] = get_sibilings($terms, $second_level['tid']);
        }
    }

    olLiTree($main_term_list, 0);

}

function get_sibilings($terms, $parent) {
    $temp_list = [];

    foreach($terms as $term) {
        if ($term->parents[0] == $parent) {
            $temp_list[] = ['tid' => $term->tid, 'name' => $term->name, 'children' => []];
        }
    }

    return $temp_list;
}

function olLiTree( $tree, $level ) {
    echo '<ul class="menu_level_' . $level . '">';
    foreach ( $tree as $item ) {
        
        if($level == '2') {
           echo "<li><a href=\"/" . drupal_get_path_alias('taxonomy/term/' . $item['tid']) . "\" id=\"$item[tid]\" data-level=\"$level\">$item[name]</a>";
       }
       else{
           echo "<li><a href=\"javascript:\" id=\"$item[tid]\" data-level=\"$level\">$item[name]</a>";
       }

        if (isset( $item['children'])  && count($item['children'])) {
            olLiTree( $item['children'], ++$level );
        }

        --$level;
        echo "</li>";
    }

    echo '</ul>';
}